version: '3'
services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:9000"
    command: ["--no-auth"]
  web:
    image: nginx
    volumes:
      - ./robot/report:/usr/share/nginx/html
    ports:
      - "8082:80"

  development-overview:
    image: ckleinhuis/ufp-env-handlebars:latest
    environment:
      - "CFG_BRAND_LABEL=Dev Ufp-Env-Handlebars-Docker"
      - "CFG_MENU_0_LABEL=Portainer"
      - "CFG_MENU_0_LINK=http://localhost:8081"
      - "CFG_MENU_0_TARGET=portainer"
      - "CFG_MENU_1_LABEL=Test Report"
      - "CFG_MENU_1_LINK=http://localhost:8082"
      - "CFG_WELCOME_ENTRIES_0_TEXTS_0_TITLE=Ufp Env Handlebars Debug Entry Point"
      - "CFG_WELCOME_ENTRIES_0_TEXTS_0_TEXT=This is just a debug overview entrypoint, a portaines ist started, and 2 services run, funny enough its the same service used to render this page"

      - "CFG_WELCOME_ENTRIES_0_BUTTONS_0_LABEL=Portainer"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_0_DESCRIPTION=For showing debug functionality usage of SIDT paradigm a Portainer is started up in debug stack"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_0_LINK=http://localhost:8081"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_0_TARGET=portainer"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_0_COLOR=secondary"

      - "CFG_WELCOME_ENTRIES_0_BUTTONS_1_LABEL=Ufp Env Handlebars example 1"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_3_LINK=http://localhost:3000"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_1_DESCRIPTION=Show the service configured for example 1 testing properties for welcome and menu"

      - "CFG_WELCOME_ENTRIES_0_BUTTONS_2_LABEL=Ufp Env Handlebars example 2"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_2_LINK=http://localhost:3001"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_2_DESCRIPTION=A double check, having the service a second time around with different env values"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_2_COLOR=primary"

      - "CFG_WELCOME_ENTRIES_0_BUTTONS_3_LABEL=Test Report"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_3_LINK=http://localhost:8082/report.html"
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_3_DESCRIPTION=RobotFramework Test Report, use  './sidt.sh -u test -c' for creating new report, and restart debug stack using './sidt.sh -u test -c' "
      - "CFG_WELCOME_ENTRIES_0_BUTTONS_3_COLOR=success"

    ports:
      - "8080:3000"

  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - development-overview

