version: '2'
services:
  ufp-env-handlebars:
    image: ckleinhuis/ufp-env-handlebars:latest
    environment:
    - "CFG_MENU_0_LABEL=UFP"
    - "CFG_MENU_0_LINK=https://frontendsolutions.de/"
    - "CFG_MENU_0_COLOR=btn-primary"
    - "CFG_MENU_0_CHILDREN_0_LABEL=Welcome"
    - "CFG_MENU_0_CHILDREN_0_LINK=https://frontendsolutions.de/#/enterprise"
    - "CFG_MENU_0_CHILDREN_0_COLOR=btn-primary"

    - "CFG_MENU_0_CHILDREN_1_LABEL=More"
    - "CFG_MENU_0_CHILDREN_1_LINK=https://frontendsolutions.de/#/startup"
    - "CFG_MENU_0_CHILDREN_1_COLOR=btn-secondary"

    - "CFG_MENU_1_LABEL=github.com"
    - "CFG_MENU_1_TARGET=ufp github"
    - "CFG_MENU_1_COLOR=btn-secondary"
    - "CFG_MENU_1_LINK=https://github.com/FrontendSolutionsGmbH"

    - "CFG_MENU_2_LABEL=MENU 2"
    - "CFG_MENU_2_COLOR=btn-secondary"
    - "CFG_MENU_2_LINK=https://frontendsolutions.de/"

    - "CFG_MENU_3_LABEL=MENU 3"
    - "CFG_MENU_3_COLOR=btn-secondary"
    - "CFG_MENU_3_LINK=https://frontendsolutions.de/"
    - "CFG_WELCOME_ENTRIES_0_TEXTS_0_TITLE=Welcome to this example"
    - "CFG_WELCOME_ENTRIES_0_TEXTS_0_TEXT=Welcome to this example"
    ports:
    - "3000:3000"



  ufp-env-handlebars2:
    image: ckleinhuis/ufp-env-handlebars:latest
    environment:
    - "CFG_MENU_0_LABEL=SERVICE 2"
    - "CFG_MENU_0_LINK=http://www.froso.de"
    - "CFG_MENU_0_COLOR=w3-blue"

    ports:
    - "3001:3000"

  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - ufp-env-handlebars
